### ISSUE TITLE
Using the 'default' aws profile when getting layer version

### ISSUE THREAD

**Issue by evdh** [blaxk/serverless-aws-latest-layer-version#1]
I'm not sure if this is related to this plugin (I've been using this plugin for a long time without any issues), so please close if this issue is not related. Maybe it has to do with a recent upgrade from the serverless framework or something else.

I recently got errors because it seemed that while getting the latest layer version, it uses a different aws profile (as defined in .aws/credentials) than what the serverless framework is using. I have 2 profiles defined, 'default' and 'my-test-profile'. Now, when I deploy like this:

sls deploy --stage test --aws-profile my-test-profile

I get the following error:

An error occurred: UserGetLambdaFunction - 1 validation error detected: Value '[arn:aws:lambda:eu-west-1:2222222222:layer:test-project-admin-layer:AccessDeniedException: User: arn:aws:iam::5555555555:user/serverless-admin is not authorized to perform: lambda:ListLayerVersions on resource: arn:aws:lambda:eu-west-1:2222222222:layer:test-project-admin-layer]' at 'layers' failed to satisfy constraint: Member must satisfy constraint: [Member must have length less than or equal to 140, Member must have length greater than or equal to 1, Member must satisfy regular expression pattern: (arn:[a-zA-Z0-9-]+:lambda:[a-zA-Z0-9-]+:\d{12}:layer:[a-zA-Z0-9-_]+:[0-9]+)|(arn:[a-zA-Z0-9-]+:lambda:::awslayer:[a-zA-Z0-9-_]+)]

The user trying to perform the 'lambda:ListLayerVersions' is the user from the **default** profile and not the **my-test-profile** profile.

**Comment by blaxk** [comment]
thank you "evdh"

I  released a modified version.
Please check the README for more details.
